FROM ubuntu:xenial
MAINTAINER PastaGringo <pastagringo@protonmail.com>

RUN useradd -ms /bin/bash johndoe 

RUN apt-get update && apt-get install -y \
		build-essential \
		irssi \
		irssi-dev \
		libglib2.0-dev \
		libssl-dev \
		cmake \
		git 

USER johndoe
WORKDIR /home/johndoe

RUN git clone https://github.com/falsovsky/FiSH-irssi.git; \
	cd FiSH-irssi; \
    cmake -DCMAKE_BUILD_TYPE=Release ../; \
    make \
	make install \
	mkdir /home/johndoe/.irssi \
	echo "load /usr/local/lib/irssi/modules/libfish.so" >> /home/johndoe/.irssi/startup

CMD ["irssi"]
