FROM ubuntu:xenial

RUN apt-get update && apt-get install -y \
		build-essential \
		irssi \
		irssi-dev \
		libglib2.0-dev \
		libssl-dev \
		cmake \
		git \

RUN cd /root
RUN git clone https://github.com/falsovsky/FiSH-irssi.git
RUN cd FiSH-irssi
RUN cmake .
RUN make
RUN make install
RUN echo "load /usr/local/lib/irssi/modules/libfish.so" >> /root/.irssi/startup

CMD ["irssi"]
