FROM ubuntu:xenial
MAINTAINER PastaGringo <pastagringo@protonmail.com>

RUN 	apt-get update && apt-get install -y \
	build-essential \
	irssi \
	irssi-dev \
	libglib2.0-dev \
	libssl-dev \
	cmake \
	git 

RUN 	cd /tmp; \
	git clone https://github.com/falsovsky/FiSH-irssi.git; \
	cd FiSH-irssi; \
    	cmake -DCMAKE_BUILD_TYPE=Release ../; \
    	make \
	make install \
	echo "load /usr/local/lib/irssi/modules/libfish.so" >> /root/.irssi/startup

CMD ["irssi"]
